[tools]
fd = "latest"
jq = "latest"
ripgrep = "latest"
uv = "latest"

node = ["24"]

python = ["3.14"]
"pipx:huggingface-hub" = { version = "latest", uvx_args = "--no-python-downloads --python 3.14" }
#"pipx:oci-cli" = { version = "latest", uvx_args = "--no-python-downloads --python 3.12" }

"npm:cline" = "latest"
"github:JetBrains/thinkrail" = "latest"
pi = "latest" # aqua:earendil-works/pi
opencode = "latest" # aqua:anomalyco/opencode