FROM docker.io/library/debian:13-slim

ARG BUILD_DATE
ARG UID=1000
ARG GID=1000
ARG USER=dev

# RUN apt-get update && \
# apt-get -y --no-install-recommends upgrade && \
# apt-get -y --no-install-recommends install \
# && \
# apt-get autoremove && \
# apt-get clean && \
# rm -rf /var/lib/apt/lists/*

# RUN install -dm 755 /etc/apt/keyrings && \
# curl -fSs https://mise.en.dev/gpg-key.pub | tee /etc/apt/keyrings/mise-archive-keyring.asc 1>/dev/null && \
# echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.asc] https://mise.en.dev/deb stable main" | tee /etc/apt/sources.list.d/mise.list
# WORKDIR /usr/local/bin

# FROM base-debian-slim

# COPY --from=intermediate /etc/apt/keyrings/mise-archive-keyring.asc /etc/apt/keyrings/mise-archive-keyring.asc
# COPY --from=intermediate /etc/apt/sources.list.d/mise.list  /etc/apt/sources.list.d/mise.list

# RUN dnf copr enable jdxcode/mise && sudo dnf install mise

RUN apt-get update && \
apt-get -y --no-install-recommends upgrade && \
apt-get -y --no-install-recommends install extrepo ca-certificates curl git sudo vim-tiny && \
extrepo enable mise && \
apt-get update && \
apt-get -y --no-install-recommends install mise && \
apt-get autoremove && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

RUN groupadd --gid ${GID} ${USER} && \
    useradd --uid ${UID} --gid ${GID} --create-home --shell /bin/bash ${USER} && \
    echo "${USER} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER} && \
    mkdir -p -- /home/${USER}/.config/mise /home/${USER}/.cache/huggingface/hub /home/${USER}/.pi

COPY config.toml /home/${USER}/.config/mise/config.toml

RUN chmod 0440 /etc/sudoers.d/${USER} && chown ${UID}:${GID} -R /home/${USER}

USER ${USER}

ENV \
HOME="/home/${USER}" \
MISE_MINIMUM_RELEASE_AGE="3d" \
npm_config_ignore_scripts=true \
npm_config_min_release_age=3 \
PIP_REQUIRE_VIRTUALENV="true" \
PIP_UPLOADED_PRIOR_TO="P3D" \
pnpm_config_minimum_release_age=4320 \
UV_EXCLUDE_NEWER="3 days" \
PATH="/home/${USER}/.local/share/mise/shims:${PATH}"

WORKDIR /home/${USER}

RUN git config --global --add safe.directory '*' && \
    mise install

ENTRYPOINT ["/usr/bin/env"]

CMD ["/usr/bin/bash"]
