FROM docker.io/library/debian:13-slim AS base-debian-slim

ARG BUILD_DATE
ARG UID=1000
ARG GID=1000

RUN apt-get update && \
apt-get -y --no-install-recommends upgrade && \
apt-get -y --no-install-recommends install \
ca-certificates \
curl \
git \
sudo \
vim-tiny \
&& \
apt-get autoremove && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

FROM base-debian-slim AS intermediate

RUN install -dm 755 /etc/apt/keyrings && \
curl -fSs https://mise.en.dev/gpg-key.pub | tee /etc/apt/keyrings/mise-archive-keyring.asc 1>/dev/null && \
echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.asc] https://mise.en.dev/deb stable main" | tee /etc/apt/sources.list.d/mise.list
WORKDIR /usr/local/bin

FROM base-debian-slim

COPY --from=intermediate /etc/apt/keyrings/mise-archive-keyring.asc /etc/apt/keyrings/mise-archive-keyring.asc
COPY --from=intermediate /etc/apt/sources.list.d/mise.list  /etc/apt/sources.list.d/mise.list

RUN apt-get update && \
apt-get -y --no-install-recommends upgrade && \
apt-get -y --no-install-recommends install \
mise \
&& \
apt-get autoremove && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

RUN groupadd --gid ${GID} dev && \
    useradd --uid ${UID} --gid ${GID} --create-home --shell /bin/bash dev && \
    echo 'dev ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/dev && \
    chmod 0440 /etc/sudoers.d/dev

USER dev

COPY config.toml /home/dev/.config/mise/config.toml

ENV \
HOME="/home/dev" \
MISE_MINIMUM_RELEASE_AGE="3d" \
npm_config_ignore_scripts=true \
npm_config_min_release_age=3 \
PIP_REQUIRE_VIRTUALENV="true" \
PIP_UPLOADED_PRIOR_TO="P3D" \
pnpm_config_minimum_release_age=4320 \
UV_EXCLUDE_NEWER="3 days" \
PATH="/home/dev/.local/share/mise/shims:${PATH}"

WORKDIR /home/dev

RUN git config --global --add safe.directory '*' && \
    mise install && \
    mkdir -p -- ~/.config/mise ~/.cache/huggingface/hub ~/.pi

ENTRYPOINT ["/usr/bin/env"]

CMD ["/usr/bin/bash"]
