# @see https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md
# @see https://github.com/mostlygeek/llama-swap/blob/main/config.example.yaml
# @see https://github.com/mostlygeek/llama-swap/blob/main/docker/config.example.yaml
# @see https://github.com/mostlygeek/llama-swap/blob/main/docs/configuration.md
# @see https://gabriel.devenyi.ca/huggingface-estimate/
# default ollama quant: Q4_K_M

globalTTL: 0
healthCheckTimeout: 600
includeAliasesInList: false
startPort: 5800

captureBuffer: 10
logLevel: debug
logRequests: true
logTimeFormat: "RFC3339"
logToStdout: both
metricsMaxInMemory: 1000
performance:
  disabled: false
  every: 10s
sendLoadingState: false

macros:
  # -ot ".ffn_.*_exps.=CPU" # offloads all MoE layers to the CPU
  # -ot ".ffn_(up|down)_exps.=CPU"
  # -ot ".ffn_(up)_exps.=CPU"
  # --cpu-moe
  # --no-kv-offload
  # --fit-ctx  65536
  # --fit-ctx 131072
  # --fit-ctx 262144
  # --ctx-size 262144
  "L_PREFIX": >
    llama-server --hf-repo ${MODEL_ID} --port ${PORT} --prio 2
    --log-verbosity 4

    --batch-size 512
    --log-colors off
    --no-mmproj-offload
    --no-ui
    --no-warmup
    --ubatch-size 128

    --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2
    --cache-type-k q8_0
    --cache-type-k-draft q8_0
    --spec-draft-type-k q8_0
    --cache-type-v q8_0
    --cache-type-v-draft q8_0
    --spec-draft-type-v q8_0

    --fit on
    --fit-ctx 65536
    --fit-target 1024
    --n-predict 65536
    --no-context-shift
  # https://unsloth.ai/docs/models/tutorials/devstral-2#devstral-small-2-24b
  "D_DEVSTR": "--temp 0.15"
  # https://unsloth.ai/docs/models/qwen3.6#qwen3.6-35b-a3b
  # W load_hparams: Qwen-VL models require at minimum 1024 image tokens to function correctly on grounding tasks
  # W load_hparams: if you encounter problems with accuracy, try adding --image-min-tokens 1024
  # W load_hparams: more info: https://github.com/ggml-org/llama.cpp/issues/16842
  "D_QWEN36": >
    --image-min-tokens 1024

    --temp 0.6
    --top-p 0.95
    --top-k 20
    --repeat-penalty 1.00
    --presence-penalty 0.00
    --min-p 0.00
    --chat-template-kwargs '{"preserve_thinking": true}'
    --reasoning-budget 16384 --reasoning-budget-message "
    
    Considering the limited time by the user, I have to give the solution based on the thinking directly now.
    </think>.
    
    "
  "D_GEMMA4": "--temp 1.0 --top-p 0.95 --top-k 64" # https://unsloth.ai/docs/models/gemma-4#llama.cpp-guide
  "D_GLM47F": "--temp 0.7 --top-p 1.0 --min-p 0.01 --repeat-penalty 1.00"
  
  #"D_GPTOSS": "--temp 1.0 --min-p 0.0 --top-p 1.0 --top-k 0"
  #"D_GRAN41": "--temp 0.0 --top-k 0 --top-p 1.0"
  #"D_NTP": ""  
  #"D_MTP": "--spec-type draft-mtp --spec-draft-n-max 3" # https://unsloth.ai/docs/models/qwen3.6#llama.cpp-mtp-guide
apiKeys:
  - "${env.LLAMASWAP_API_KEY}"
models:
  "byteshape/Devstral-Small-2-24B-Instruct-2512-GGUF:IQ4_XS":     {cmd:  "${L_PREFIX}  ${D_DEVSTR}"}

  "unsloth/gemma-4-12b-it-GGUF:UD-Q6_K_XL":                       {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}
  "unsloth/gemma-4-12b-it-GGUF:UD-Q8_K_XL":                       {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}
  "unsloth/gemma-4-12B-it-qat-GGUF:UD-Q4_K_XL":                   {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}
  "unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q6_K_XL":                   {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}
  "unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q8_K_XL":                   {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}
  "unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL":               {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}

  "unsloth/GLM-4.7-Flash-GGUF:UD-Q6_K_XL":                        {cmd:  "${L_PREFIX}  ${D_GLM47F}"}
  "unsloth/GLM-4.7-Flash-GGUF:UD-Q8_K_XL":                        {cmd:  "${L_PREFIX}  ${D_GLM47F}"}

  "byteshape/Qwen3.6-35B-A3B-GGUF:Q4_K_S":                        {cmd:  "${L_PREFIX}  ${D_QWEN36}  --hf-file  Qwen3.6-35B-A3B-Q4_K_S-4.22bpw.gguf"}
  "unsloth/Qwen3.6-27B-GGUF:Q4_K_M":                              {cmd:  "${L_PREFIX}  ${D_QWEN36}"}
  "unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q6_K_XL":                      {cmd:  "${L_PREFIX}  ${D_QWEN36}"}
  "unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q8_K_XL":                      {cmd:  "${L_PREFIX}  ${D_QWEN36}"}

  #"unsloth/Devstral-Small-2-24B-Instruct-2512-GGUF:UD-Q8_K_XL":  {cmd:  "${L_PREFIX}  ${D_DEVSTR}"}
  #"unsloth/gemma-4-31B-it-GGUF:UD-Q8_K_XL":                      {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}
  #"unsloth/gemma-4-31B-it-qat-GGUF:UD-Q4_K_XL":                  {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}
  #"unsloth/gemma-4-E2B-it-qat-GGUF:UD-Q4_K_XL":                  {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}
  #"unsloth/gemma-4-E4B-it-qat-GGUF:UD-Q4_K_XL":                  {cmd:  "${L_PREFIX}  ${D_GEMMA4}"}
  #"unsloth/granite-4.1-3b-GGUF:UD-Q8_K_XL":                      {cmd:  "${L_PREFIX}  ${D_GRAN41}"}
  #"unsloth/granite-4.1-8b-GGUF:UD-Q8_K_XL":                      {cmd:  "${L_PREFIX}  ${D_GRAN41}"}
  #"byteshape/Qwen3.6-35B-A3B-GGUF:Q4_K_S":                       {cmd:  "${L_PREFIX}  ${D_QWEN36}"}
  #"unsloth/Qwen3.6-27B-GGUF:UD-Q8_K_XL":                         {cmd:  "${L_PREFIX}  ${D_QWEN36}"}
