{
  "globalTTL": 0,
  "healthCheckTimeout": 600,
  "includeAliasesInList": false,
  "startPort": 5800,
  "captureBuffer": 10,
  "logLevel": "debug",
  "logRequests": true,
  "logTimeFormat": "RFC3339",
  "logToStdout": "both",
  "metricsMaxInMemory": 1000,
  "performance": {
    "disabled": false,
    "every": "10s"
  },
  "sendLoadingState": false,
  "apiKeys": [
    "${env.LLAMASWAP_API_KEY}"
  ],
  "ui": {
    "activity": {
      "session_id": [
        "X-Session-ID",
        "X-Litellm-Session-Id"
      ]
    }
  },
  "hooks": {},
  "profiles": {},
  "selectors": {},
  "routing": {},
  "models": {
    "a03b-q4-k80v80-ctx200-byteshape/Qwen3.6-35B-A3B": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --image-min-tokens 1024 --temp 0.6 --top-p 0.95 --top-k 20 --repeat-penalty 1.00 --presence-penalty 0.00 --min-p 0.00 --chat-template-kwargs '{\"preserve_thinking\": true}' --reasoning-budget 16384 --reasoning-budget-message \"\nConsidering the limited time by the user, I have to give the solution based on the thinking directly now.\n</think>.\n\n\" --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 200000 --model /root/.cache/huggingface/hub/models-local/byteshape/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-Q4_K_S-4.22bpw.gguf --mmproj /root/.cache/huggingface/hub/models-local/byteshape/Qwen3.6-35B-A3B-GGUF/mmproj-bf16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a03b-q4-k80v80-ctx200-poolside/Laguna-XS-2.1-GGUF": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --reasoning-budget 16384 --reasoning-budget-message \"\nConsidering the limited time by the user, I have to give the solution based on the thinking directly now.\n</think>.\n\n\" --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 200000 --model /root/.cache/huggingface/hub/models-local/poolside/Laguna-XS-2.1-GGUF/Laguna-XS-2.1-Q4_K_M.gguf",
      "capabilities": {
        "in": [
          "text"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a03b-q6-k80v51-ctx128-unsloth/GLM-4.7-Flash": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 0.7 --top-p 1.0 --min-p 0.01 --repeat-penalty 1.00 --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q5_1 --cache-type-v-draft q5_1 --spec-draft-type-v q5_1 --fit-ctx 131072 --model /root/.cache/huggingface/hub/models-local/unsloth/GLM-4.7-Flash-GGUF/GLM-4.7-Flash-Q6_K.gguf",
      "capabilities": {
        "in": [
          "text"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a03b-q6-k80v80-ctx128-unsloth/Qwen3.6-35B-A3B": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --image-min-tokens 1024 --temp 0.6 --top-p 0.95 --top-k 20 --repeat-penalty 1.00 --presence-penalty 0.00 --min-p 0.00 --chat-template-kwargs '{\"preserve_thinking\": true}' --reasoning-budget 16384 --reasoning-budget-message \"\nConsidering the limited time by the user, I have to give the solution based on the thinking directly now.\n</think>.\n\n\" --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 131072 --model /root/.cache/huggingface/hub/models-local/unsloth/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-UD-Q6_K.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/Qwen3.6-35B-A3B-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a03b-q8-k80v51-ctx128-unsloth/GLM-4.7-Flash": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 0.7 --top-p 1.0 --min-p 0.01 --repeat-penalty 1.00 --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q5_1 --cache-type-v-draft q5_1 --spec-draft-type-v q5_1 --fit-ctx 131072 --model /root/.cache/huggingface/hub/models-local/unsloth/GLM-4.7-Flash-GGUF/GLM-4.7-Flash-Q8_0.gguf",
      "capabilities": {
        "in": [
          "text"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a03b-q8-k80v80-ctx128-unsloth/Qwen3.6-35B-A3B": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --image-min-tokens 1024 --temp 0.6 --top-p 0.95 --top-k 20 --repeat-penalty 1.00 --presence-penalty 0.00 --min-p 0.00 --chat-template-kwargs '{\"preserve_thinking\": true}' --reasoning-budget 16384 --reasoning-budget-message \"\nConsidering the limited time by the user, I have to give the solution based on the thinking directly now.\n</think>.\n\n\" --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 131072 --model /root/.cache/huggingface/hub/models-local/unsloth/Qwen3.6-35B-A3B-GGUF/Qwen3.6-35B-A3B-Q8_0.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/Qwen3.6-35B-A3B-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a04b-q4-k80v80-ctx256-unsloth/gemma-4-26B-A4B-qat": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 1.0 --top-p 0.95 --top-k 64 --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 262144 --model /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-26B-A4B-it-qat-GGUF/gemma-4-26B-A4B-it-qat-UD-Q4_K_XL.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-26B-A4B-it-qat-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a04b-q6-k80v80-ctx128-unsloth/gemma-4-26B-A4B": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 1.0 --top-p 0.95 --top-k 64 --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 131072 --model /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-26B-A4B-it-GGUF/gemma-4-26B-A4B-it-UD-Q6_K.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-26B-A4B-it-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a04b-q8-k80v80-ctx128-unsloth/gemma-4-26B-A4B": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 1.0 --top-p 0.95 --top-k 64 --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 131072 --model /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-26B-A4B-it-GGUF/gemma-4-26B-A4B-it-Q8_0.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-26B-A4B-it-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a12b-q4-k80v80-ctx256-unsloth/gemma-4-12b-qat": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 1.0 --top-p 0.95 --top-k 64 --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 262144 --model /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-12B-it-qat-GGUF/gemma-4-12B-it-qat-UD-Q4_K_XL.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-12B-it-qat-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a12b-q6-k80v80-ctx256-unsloth/gemma-4-12b": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 1.0 --top-p 0.95 --top-k 64 --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 262144 --model /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-12b-it-GGUF/gemma-4-12b-it-Q6_K.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-12b-it-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a12b-q8-k80v80-ctx200-unsloth/gemma-4-12b": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 1.0 --top-p 0.95 --top-k 64 --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q8_0 --cache-type-v-draft q8_0 --spec-draft-type-v q8_0 --fit-ctx 200000 --model /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-12b-it-GGUF/gemma-4-12b-it-Q8_0.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-12b-it-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a24b-q4-k80v51-ctx064-byteshape/Devstral-Small-2-24B": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 0.15 --cache-type-k q8_0 --cache-type-k-draft q8_0 --spec-draft-type-k q8_0 --cache-type-v q5_1 --cache-type-v-draft q5_1 --spec-draft-type-v q5_1 --fit-ctx 65536 --model /root/.cache/huggingface/hub/models-local/byteshape/Devstral-Small-2-24B-Instruct-2512-GGUF/Devstral-Small-2-24B-Instruct-2512-IQ4_XS-4.04bpw.gguf --mmproj /root/.cache/huggingface/hub/models-local/byteshape/Devstral-Small-2-24B-Instruct-2512-GGUF/mmproj-bf16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a27b-q4-k50v41-ctx064-unsloth/Qwen3.6-27B": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --image-min-tokens 1024 --temp 0.6 --top-p 0.95 --top-k 20 --repeat-penalty 1.00 --presence-penalty 0.00 --min-p 0.00 --chat-template-kwargs '{\"preserve_thinking\": true}' --reasoning-budget 16384 --reasoning-budget-message \"\nConsidering the limited time by the user, I have to give the solution based on the thinking directly now.\n</think>.\n\n\" --cache-type-k q5_0 --cache-type-k-draft q5_0 --spec-draft-type-k q5_0 --cache-type-v q4_1 --cache-type-v-draft q4_1 --spec-draft-type-v q4_1 --fit-ctx 65536 --model /root/.cache/huggingface/hub/models-local/unsloth/Qwen3.6-27B-GGUF/Qwen3.6-27B-Q4_K_M.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/Qwen3.6-27B-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    },
    "a31b-q4-k50v41-ctx064-unsloth/gemma-4-31B-qat": {
      "cmd": "llama-server --port ${PORT} --prio 2 --log-verbosity 4 --threads-http 6 --batch-size 512 --log-colors off --no-mmproj-offload --no-ui --no-warmup --ubatch-size 128 --cache-idle-slots --kv-unified --cache-ram 8192 --flash-attn on --parallel 2 --fit on --fit-target 1024 --n-predict 100000 --no-context-shift --temp 1.0 --top-p 0.95 --top-k 64 --cache-type-k q5_0 --cache-type-k-draft q5_0 --spec-draft-type-k q5_0 --cache-type-v q4_1 --cache-type-v-draft q4_1 --spec-draft-type-v q4_1 --fit-ctx 65536 --model /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-31B-it-qat-GGUF/gemma-4-31B-it-qat-UD-Q4_K_XL.gguf --mmproj /root/.cache/huggingface/hub/models-local/unsloth/gemma-4-31B-it-qat-GGUF/mmproj-F16.gguf",
      "capabilities": {
        "in": [
          "text",
          "image"
        ],
        "out": [
          "text"
        ]
      }
    }
  },
  "peers": {
    "openrouter-free": {
      "proxy": "https://openrouter.ai/api",
      "models": [
        "inclusionai/ling-3.0-flash:free",
        "poolside/laguna-s-2.1:free",
        "poolside/laguna-xs-2.1:free",
        "cohere/north-mini-code:free",
        "nvidia/nemotron-3.5-content-safety:free",
        "nvidia/nemotron-3-ultra-550b-a55b:free",
        "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
        "google/gemma-4-26b-a4b-it:free",
        "google/gemma-4-31b-it:free",
        "nvidia/nemotron-3-super-120b-a12b:free",
        "nvidia/nemotron-3-nano-30b-a3b:free",
        "nvidia/nemotron-nano-12b-v2-vl:free",
        "nvidia/nemotron-nano-9b-v2:free",
        "openai/gpt-oss-20b:free"
      ],
      "apiKey": "${env.__OPENROUTER_API_KEY}"
    },
    "opencode-zen-free": {
      "proxy": "https://opencode.ai/zen",
      "models": [
        "deepseek-v4-flash-free",
        "mimo-v2.5-free",
        "ling-3.0-flash-free",
        "nemotron-3-ultra-free",
        "north-mini-code-free",
        "laguna-s-2.1-free",
        "longcat-2.0-free"
      ],
      "apiKey": "${env.__OPENCODE_ZEN_API_KEY}"
    },
    "opencode-go-sub": {
      "proxy": "https://opencode.ai/zen/go",
      "models": [
        "minimax-m3",
        "minimax-m2.7",
        "minimax-m2.5",
        "kimi-k3",
        "kimi-k2.7-code",
        "kimi-k2.6",
        "kimi-k2.5",
        "glm-5.2",
        "glm-5.1",
        "glm-5",
        "deepseek-v4-pro",
        "deepseek-v4-flash",
        "qwen3.7-max",
        "qwen3.8-max",
        "qwen3.7-plus",
        "qwen3.6-plus",
        "qwen3.5-plus",
        "mimo-v2-pro",
        "mimo-v2-omni",
        "mimo-v2.5-pro",
        "mimo-v2.5",
        "hy3",
        "hy3-preview",
        "gpt-5.6-luna",
        "grok-4.5"
      ],
      "apiKey": "${env.__OPENCODE_GO_API_KEY}"
    }
  }
}
